import { contextBridge, ipcRenderer } from 'electron'
import { IPC_CHANNELS } from '@shared/constants'

/**
 * 安全 preload 桥（第二轮审计 P0-1 修复）：
 * 1. 通道白名单：仅允许显式声明的通道，防止 XSS/恶意页面调用任意 IPC
 * 2. 渲染进程只能 invoke 白名单内的通道，其余一律拒绝
 */

/** 允许渲染进程调用的通道白名单（显式声明，新增通道需在此登记） */
const ALLOWED_INVOKE_CHANNELS: string[] = [
  // ── 认证 ──
  IPC_CHANNELS.AUTH_LOGIN,
  IPC_CHANNELS.AUTH_LIST_USERS,
  IPC_CHANNELS.AUTH_CREATE_USER,
  IPC_CHANNELS.AUTH_CHANGE_PASSWORD,
  IPC_CHANNELS.AUTH_RESET_PASSWORD,
  IPC_CHANNELS.AUTH_LOGOUT,
  // ── 区域 ──
  IPC_CHANNELS.REGION_LIST,
  IPC_CHANNELS.REGION_GET,
  IPC_CHANNELS.REGION_CREATE,
  IPC_CHANNELS.REGION_UPDATE,
  IPC_CHANNELS.REGION_DELETE,
  // ── 合同 ──
  IPC_CHANNELS.CONTRACT_LIST,
  IPC_CHANNELS.CONTRACT_GET,
  IPC_CHANNELS.CONTRACT_CREATE,
  IPC_CHANNELS.CONTRACT_UPDATE,
  IPC_CHANNELS.CONTRACT_DELETE,
  IPC_CHANNELS.CONTRACT_APPROVE,
  IPC_CHANNELS.CONTRACT_BATCH_APPROVE,
  IPC_CHANNELS.CONTRACT_SUMMARIZE,
  IPC_CHANNELS.CONTRACT_LIST_VERSIONS,
  IPC_CHANNELS.CONTRACT_TYPE_LIST,
  // ── 公司 ──
  IPC_CHANNELS.COMPANY_LIST,
  IPC_CHANNELS.COMPANY_GET,
  IPC_CHANNELS.COMPANY_CREATE,
  IPC_CHANNELS.COMPANY_UPDATE,
  IPC_CHANNELS.COMPANY_DELETE,
  // ── 资金 ──
  IPC_CHANNELS.ACCOUNT_LIST,
  IPC_CHANNELS.ACCOUNT_GET,
  IPC_CHANNELS.ACCOUNT_CREATE,
  IPC_CHANNELS.ACCOUNT_SUMMARY,
  IPC_CHANNELS.ACCOUNT_YEARS,
  IPC_CHANNELS.ACCOUNT_TRANSACTIONS,
  IPC_CHANNELS.ACCOUNT_ADD_TRANSACTION,
  // ── 模拟计算 / 基础设施 ──
  IPC_CHANNELS.FORMULA_CALCULATE,
  IPC_CHANNELS.FORMULA_LOG_LIST,
  IPC_CHANNELS.INFRA_TYPE_LIST,
  IPC_CHANNELS.INFRA_CALC_LOAD,
  // ── 土地报告 ──
  IPC_CHANNELS.REPORT_LAND_AREA,
  IPC_CHANNELS.REPORT_LAND_AREA_BY_REGION,
  // ── 公告 ──
  IPC_CHANNELS.ANNOUNCEMENT_LIST,
  IPC_CHANNELS.ANNOUNCEMENT_ACTIVE_LIST,
  IPC_CHANNELS.ANNOUNCEMENT_CREATE,
  IPC_CHANNELS.ANNOUNCEMENT_DELETE,
  // ── 认证（补充）──
  IPC_CHANNELS.AUTH_DELETE_USER,
  // ── 通知 ──
  IPC_CHANNELS.NOTIFICATION_LIST,
  IPC_CHANNELS.NOTIFICATION_MARK_READ,
  IPC_CHANNELS.NOTIFICATION_UNREAD_COUNT,
  // ── 审计 ──
  IPC_CHANNELS.AUDIT_LIST,
  // ── 系统 ──
  IPC_CHANNELS.SYSTEM_HEALTH,
  IPC_CHANNELS.DASHBOARD_SUMMARY,
  IPC_CHANNELS.DASHBOARD_SYSTEM_STATS,
  // ── 凭据（统一登录）──
  IPC_CHANNELS.CREDENTIAL_SET,
  IPC_CHANNELS.CREDENTIAL_GET,
  // ── 数据管理 ──
  IPC_CHANNELS.DB_BACKUP_TO_DESKTOP,
  IPC_CHANNELS.DB_RESTORE,
  IPC_CHANNELS.DB_INFO,
  IPC_CHANNELS.DB_AUTO_BACKUP,
  IPC_CHANNELS.EXCEL_EXPORT,
  IPC_CHANNELS.EXCEL_EXPORT_CONTRACTS,
  IPC_CHANNELS.EXCEL_EXPORT_REGIONS,
  IPC_CHANNELS.EXCEL_EXPORT_ACCOUNT_TRANSACTIONS,
  IPC_CHANNELS.EXCEL_IMPORT,
  // ── 股票同步日志（设置页展示）──
  IPC_CHANNELS.STOCK_SYNC_LOG,
  IPC_CHANNELS.STOCK_GET_MARKET,
  // ── 其他（UI 辅助）──
  IPC_CHANNELS.GIPFEL_OPEN,
]

/** 允许渲染进程订阅的事件通道 */
const ALLOWED_ON_CHANNELS: string[] = [
  IPC_CHANNELS.NOTIFICATION_CHANGED_EVENT,
]

const ALLOWED_INVOKE_SET = new Set(ALLOWED_INVOKE_CHANNELS)
const ALLOWED_ON_SET = new Set(ALLOWED_ON_CHANNELS)

contextBridge.exposeInMainWorld('api', {
  invoke: (channel: string, ...args: unknown[]) => {
    if (!ALLOWED_INVOKE_SET.has(channel)) {
      console.warn(`[preload] 已拦截未授权 IPC 通道调用: ${channel}`)
      return Promise.reject(new Error(`通道 ${channel} 未授权`))
    }
    return ipcRenderer.invoke(channel, ...args)
  },
  on: (channel: string, callback: (...args: unknown[]) => void) => {
    if (!ALLOWED_ON_SET.has(channel)) {
      console.warn(`[preload] 已拦截未授权事件订阅: ${channel}`)
      return () => { /* no-op */ }
    }
    const subscription = (_event: Electron.IpcRendererEvent, ...args: unknown[]): void =>
      callback(...args)
    ipcRenderer.on(channel, subscription)
    return () => ipcRenderer.removeListener(channel, subscription)
  }
})
